# Generated by Django 2.0.9 on 2024-12-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_images_usercart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='product',
        ),
        migrations.DeleteModel(
            name='Usercart',
        ),
    ]
