# Generated by Django 3.2.25 on 2024-12-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20241217_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_item', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('individual_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
