# Generated by Django 3.2.25 on 2024-12-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_usercart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usercart',
        ),
    ]
