# Generated by Django 3.2.25 on 2024-12-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_wish_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish_list',
        ),
    ]
