# Generated by Django 3.2.25 on 2024-12-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_profile_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
