# Generated by Django 3.2.25 on 2024-12-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20241226_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepic',
            name='resume',
            field=models.FileField(default='abc.txt', upload_to='files/resume'),
            preserve_default=False,
        ),
    ]
