# Generated by Django 3.2.25 on 2024-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(default='a.jpg', upload_to='products/'),
            preserve_default=False,
        ),
    ]
